import type { Metadata } from "next";
import { Geist_Mono, Hind_Siliguri } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/header/NavBar";
import CategoryLink from "@/components/header/CategoryLink";
import MarqueeHadeline from "@/components/header/Marquee";
import Footer from "@/components/Footer";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const hindSiliguri = Hind_Siliguri({
  variable: "--font-geist-siliguri",
  subsets: ["bengali"],
  weight: ["300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${hindSiliguri.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#f3f8f4]">
        <header>
          <NavBar></NavBar>
          <CategoryLink></CategoryLink>
          <MarqueeHadeline></MarqueeHadeline>
        </header>
        <main className="container mx-auto">
          {children}
        </main>
        <Footer></Footer>
      </body>
    </html>
  );
}
